theme = "alpha"

[editor]
mouse = true
line-number = "relative"

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "disable"

[editor.indent-guides]
character = "┊"
render = true

[keys.normal]
D = ["ensure_selections_forward", "extend_to_line_end", "delete_selection"]

# yazi
Y = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi %{buffer_name} --chooser-file=/tmp/unique-file',
  ':insert-output echo "\\x1b[?1049h\\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
]
# lazygit
G = [
  ":write-all",
  ":new",
  ":insert-output lazygit",
  ":buffer-close!",
  ":redraw",
  ":reload-all"
]

[keys.normal."space"]
B = ":sh git blame -L %{cursor_line},+1 %{buffer_name} | cut -d' ' -f1 | xargs git show -s --format='%%C(yellow)%%h  %%Cgreen%%ad  %%C(bold blue)%%an  %%Creset %%s' --date=relative"
